version: '3.8'

services:
  webnovel:
    build: .
    container_name: webnovel-app
    ports:
      - "3000:3000"    # 后端API
      - "5173:5173"    # 前端应用
    volumes:
      - webnovel_data:/app/data    # 数据持久化
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=/app/data/database.sqlite
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  webnovel_data:
    driver: local 